#ifndef NOSQLITE_STORAGE_ERROR_H
#define NOSQLITE_STORAGE_ERROR_H

#include <stdint.h>

#define NOSQLITE_OK 0

typedef enum {
    NOSQLITE_ERR_PAGE_NOT_FOUND = 1,
    NOSQLITE_ERR_DISK_READ_FAILURE,
    NOSQLITE_ERR_DISK_WRITE_FAILURE,
    NOSQLITE_ERR_FILE_CORRUPTED,
    NOSQLITE_ERR_PERMISSION_DENIED,
} StorageError;

#endif /* NOSQLITE_STORAGE_ERROR_H */
