#ifndef NOSQLITE_BUFFER_ERROR_H
#define NOSQLITE_BUFFER_ERROR_H

typedef enum {
    BUFFER_ERR_NO_AVAILABLE_FRAMES = 1,
    BUFFER_ERR_PAGE_NOT_PINNED,
    BUFFER_ERR_DISK_ERROR,
} BufferError;

#endif /* NOSQLITE_BUFFER_ERROR_H */
